/**
 * 王铁 OS — OceanBase **Oracle 兼容模式**真实实例集成测试。
 *
 * 需要一台可写的 OceanBase Oracle 模式租户，用配置文件指向它：
 *   export OB_TEST_PROFILE=.local-db/profile.json
 * 文件内容（{ mode, host, port, serviceName, user, password, tls? }）：
 *   { "mode": "oracle", "host": "10.0.0.9", "port": 2883,
 *     "serviceName": "obtenant", "user": "app@obtenant#obcluster", "password": "***" }
 * 可选 OB_TEST_SCHEMA 指定建对象的模式（默认取用户名 @ 之前的部分并大写）。
 *
 * 安全约定：只在本账号自己的模式里建 WT_OB_* 前缀的临时对象，测试结束即删除；
 * 不创建/删除用户、不触碰任何既有业务对象。请勿指向生产库。
 */

import test from 'node:test'
import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
import { createServer } from 'node:http'
import { randomBytes } from 'node:crypto'
import oracledb from 'oracledb'
import { connectionOptions, identifier } from '../src/oceanbase.ts'
import { mountOceanBase } from '../src/oceanbase-routes.ts'

const suffix = randomBytes(4).toString('hex').toUpperCase()
const TABLE = `WT_OB_T_${suffix}`
const NOKEY = `WT_OB_NOKEY_${suffix}`
const VIEW = `WT_OB_V_${suffix}`

test('real OceanBase Oracle-mode tenant over HTTP: dictionary, SQL, transactions, concurrency', { timeout: 180_000 }, async t => {
  const profile = JSON.parse((await readFile(process.env.OB_TEST_PROFILE || '.local-db/profile.json', 'utf8')).replace(/^\uFEFF/, ''))
  const options = connectionOptions(profile)
  const schema = (process.env.OB_TEST_SCHEMA || profile.schema || options.user.split('@')[0]).toUpperCase()
  const admin = await oracledb.getConnection(options)
  const target = `${identifier(schema)}.${identifier(TABLE)}`
  const created: string[] = []
  const routes: any[] = []
  const disposers = mountOceanBase({ webServer: { register: route => { routes.push(route); return () => {} } } }, '/wangtie-os')
  const server = createServer((req, res) => {
    const route = routes.find(item => item.path === req.url)
    if (!route) { res.writeHead(404); res.end(); return }
    void route.handler(req, res)
  })
  await new Promise<void>(resolve => server.listen(0, '127.0.0.1', resolve))
  const origin = `http://127.0.0.1:${(server.address() as any).port}`
  const call = async (action: string, extra: Record<string, unknown> = {}, overrides: Record<string, unknown> = {}) => {
    const response = await fetch(`${origin}/wangtie-os/api/oceanbase/${action}`, {
      method: 'POST', headers: { origin, 'content-type': 'application/json' },
      body: JSON.stringify({ connection: profile, schema, table: TABLE, ...extra, ...overrides }),
    })
    return { status: response.status, data: await response.json() as any }
  }
  const rows = async (extra: Record<string, unknown> = {}, overrides: Record<string, unknown> = {}) => {
    const result = await call('rows', extra, overrides)
    assert.equal(result.status, 200, JSON.stringify(result.data))
    return result.data
  }
  const exec = (sql: string, binds: oracledb.BindParameters = {}) => admin.execute(sql, binds, { autoCommit: true })

  try {
    await exec(`CREATE TABLE ${target} (
      ID NUMBER(19) NOT NULL,
      SEQ NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
      NAME VARCHAR2(60) NOT NULL,
      AMOUNT NUMBER(30,12),
      HIRED_AT DATE,
      BORN TIMESTAMP(6),
      RAWCOL RAW(64),
      PAYLOAD BLOB,
      NOTE CLOB,
      NAME_LEN NUMBER GENERATED ALWAYS AS (LENGTH(NAME)) VIRTUAL,
      CONSTRAINT PK_${suffix} PRIMARY KEY (ID)
    )`)
    created.push(`TABLE ${target}`)
    await exec(`CREATE TABLE ${identifier(schema)}.${identifier(NOKEY)} (NAME VARCHAR2(20))`)
    created.push(`TABLE ${identifier(schema)}.${identifier(NOKEY)}`)
    await exec(`CREATE VIEW ${identifier(schema)}.${identifier(VIEW)} AS SELECT ID, NAME FROM ${target}`)
    created.push(`VIEW ${identifier(schema)}.${identifier(VIEW)}`)
    await exec(`INSERT INTO ${target} (ID, NAME, AMOUNT, HIRED_AT, BORN, RAWCOL, PAYLOAD, NOTE)
                VALUES (9007199254740993, '初始客户', 123456789012345678.123456789012, DATE '2026-09-16',
                        TIMESTAMP '2026-09-16 13:22:33.123456', HEXTORAW('00FF275C'), HEXTORAW('00FF'), '大文本内容')`)

    await t.test('connect authenticates over the Oracle protocol and lists schemas', async () => {
      const response = await call('connect')
      assert.equal(response.status, 200, JSON.stringify(response.data))
      assert.ok(response.data.schemas.includes(schema), 'the connected schema must be listed')
      console.log('Integration engine:', response.data.info.version || '(v$version not granted)')
      const denied = await call('connect', {}, { connection: { ...profile, password: 'deliberately-wrong-password' } })
      assert.equal(denied.status, 400)
      assert.match(denied.data.error, /认证失败|服务名|无法连接/)
      assert.doesNotMatch(JSON.stringify(denied.data), /deliberately-wrong-password/)
    })

    await t.test('data dictionary lists tables (with comments) and views', async () => {
      const result = await call('tables')
      assert.equal(result.status, 200, JSON.stringify(result.data))
      const names = result.data.tables.map((item: any) => item.name)
      assert.ok(names.includes(TABLE))
      assert.ok(names.includes(NOKEY))
      const view = result.data.tables.find((item: any) => item.name === VIEW)
      assert.equal(view?.type, 'VIEW')
    })

    await t.test('NUMBER precision, DATE/TIMESTAMP, RAW/BLOB and CLOB survive reading', async () => {
      const data = await rows()
      const row = data.rows[0]
      assert.equal(row.ID, '9007199254740993', 'NUMBER must not lose precision')
      assert.equal(row.AMOUNT, '123456789012345678.123456789012')
      assert.match(row.HIRED_AT, /^2026-09-16/)
      assert.equal(row.BORN, '2026-09-16 13:22:33.123456')
      assert.equal(row.RAWCOL.binaryHex, '00ff275c')
      assert.equal(row.PAYLOAD.binaryHex, '00ff')
      assert.equal(row.NOTE, '大文本内容')
      const byName = (name: string) => data.columns.find((column: any) => column.name === name)
      assert.equal(byName('ID').primary, true)
      assert.equal(byName('SEQ').identity, true)
      assert.equal(byName('NAME_LEN').virtual, true)
      assert.equal(byName('PAYLOAD').binary, true)
      assert.equal(byName('NOTE').lob, true)
      assert.equal(byName('AMOUNT').type, 'NUMBER(30,12)')
      assert.deepEqual(data.key, { mode: 'primary', columns: ['ID'], label: '主键' })
      assert.equal(data.permissions.insert, true)
      assert.equal(data.permissions.edit, true)
    })

    await t.test('insert binds literals, stores NULL for the empty string and honours column defaults', async () => {
      const result = await call('insert', { values: { ID: '9007199254740994', NAME: "x'); DROP TABLE users; --", NOTE: '', HIRED_AT: '2026-01-02' } })
      assert.equal(result.status, 200, JSON.stringify(result.data))
      const data = await rows({ filter: { column: 'NAME', op: 'contains', value: 'DROP TABLE' } })
      assert.equal(data.rows.length, 1)
      assert.equal(data.rows[0].NOTE, null, "Oracle stores '' as NULL")
      assert.equal(data.rows[0].NAME, "x'); DROP TABLE users; --")
      assert.ok(data.rows[0].SEQ !== null && data.rows[0].SEQ !== undefined, 'identity column is generated by DEFAULT')

      const allDefault = await call('insert', { values: { ID: '9007199254740995', NAME: '全默认值插入' } })
      assert.equal(allDefault.status, 200, JSON.stringify(allDefault.data))
    })

    await t.test('duplicate primary key is rejected and does not change the row count', async () => {
      const before = await rows()
      const response = await call('insert', { values: { ID: '9007199254740993', NAME: '重复主键' } })
      assert.equal(response.status, 400)
      assert.match(response.data.error, /主键|唯一/)
      assert.equal((await rows()).rows.length, before.rows.length)
    })

    await t.test('update round-trips values and rejects invalid numbers and dates with clear messages', async () => {
      const original = (await rows({ sort: 'ID' })).rows[0]
      const ok = await call('update', { key: { ID: original.ID }, original, values: { NAME: '修改客户', AMOUNT: '0.000000000001' } })
      assert.equal(ok.status, 200, JSON.stringify(ok.data))
      const updated = (await rows()).rows.find((row: any) => row.ID === original.ID)
      assert.equal(updated.NAME, '修改客户')
      assert.equal(updated.AMOUNT, '0.000000000001')

      const badNumber = await call('update', { key: { ID: original.ID }, original: updated, values: { AMOUNT: '12a' } })
      assert.equal(badNumber.status, 400)
      assert.match(badNumber.data.error, /需要数字/)
      const badDate = await call('update', { key: { ID: original.ID }, original: updated, values: { HIRED_AT: '2026/01/02' } })
      assert.equal(badDate.status, 400)
      assert.match(badDate.data.error, /日期/)
      const nullRequired = await call('update', { key: { ID: original.ID }, original: updated, values: { NAME: '' } })
      assert.equal(nullRequired.status, 400)
      assert.match(nullRequired.data.error, /不能为 NULL/)
    })

    await t.test('a concurrent change between read and write is reported as a conflict', async () => {
      const original = (await rows()).rows[0]
      await exec(`UPDATE ${target} SET NAME = '别人改过' WHERE ID = :1`, { 1: original.ID })
      const response = await call('update', { key: { ID: original.ID }, original, values: { NOTE: 'must not overwrite' } })
      assert.equal(response.status, 409, JSON.stringify(response.data))
      const current = (await rows()).rows.find((row: any) => row.ID === original.ID)
      assert.notEqual(current.NOTE, 'must not overwrite', 'a conflicting write must not land')
    })

    await t.test('a binary-only concurrent change also blocks deletion', async () => {
      const original = (await rows()).rows[0]
      await exec(`UPDATE ${target} SET RAWCOL = HEXTORAW('DEADBEEF') WHERE ID = :1`, { 1: original.ID })
      const response = await call('delete', { key: { ID: original.ID }, original, confirm: true })
      assert.equal(response.status, 409, JSON.stringify(response.data))
    })

    await t.test('pagination and ordering keep a deterministic primary-key tie-breaker', async () => {
      const first = await rows({ limit: 1, offset: 0, sort: 'NAME' })
      const second = await rows({ limit: 1, offset: 1, sort: 'NAME' })
      assert.notEqual(first.rows[0].ID, second.rows[0].ID)
      assert.ok(first.hasMore === true || second.rows.length === 0)
    })

    await t.test('NULL and literal filters execute; bad operators and bad dates are rejected', async () => {
      const nullNote = await rows({ filter: { column: 'NOTE', op: 'null' } })
      assert.ok(nullNote.rows.length >= 1)
      assert.equal((await rows({ filter: { column: 'NAME', op: 'contains', value: 'DROP TABLE' } })).rows.length, 1)
      assert.equal((await call('rows', { filter: { column: 'NAME', op: '__proto__', value: 'x' } })).status, 400)
      assert.equal((await call('rows', { filter: { column: 'HIRED_AT', op: 'gte', value: '2026/01/02' } })).status, 400)
      assert.equal((await rows({ filter: { column: 'HIRED_AT', op: 'gte', value: '2020-01-01' } })).rows.length >= 1, true)
    })

    await t.test('a heap table without a primary key is editable through ROWID', async () => {
      const data = await rows({}, { table: NOKEY })
      assert.deepEqual(data.key, { mode: 'rowid', columns: ['wt_rowid'], label: 'ROWID' })
      assert.equal(data.permissions.edit, true)
      const inserted = await call('insert', { values: { NAME: '无主键行' } }, { table: NOKEY })
      assert.equal(inserted.status, 200, JSON.stringify(inserted.data))
      const page = await rows({}, { table: NOKEY })
      const row = page.rows[0]
      assert.ok(typeof row.wt_rowid === 'string' && row.wt_rowid.length > 0)
      const updated = await call('update', { key: { wt_rowid: row.wt_rowid }, original: row, values: { NAME: '改过的无主键行' } }, { table: NOKEY })
      assert.equal(updated.status, 200, JSON.stringify(updated.data))
      assert.equal((await rows({}, { table: NOKEY })).rows[0].NAME, '改过的无主键行')
      const deleted = await call('delete', { key: { wt_rowid: row.wt_rowid }, original: { ...row, NAME: '改过的无主键行' }, confirm: true }, { table: NOKEY })
      assert.equal(deleted.status, 200, JSON.stringify(deleted.data))
      assert.equal((await rows({}, { table: NOKEY })).rows.length, 0)
    })

    await t.test('views are query-only', async () => {
      const data = await rows({}, { table: VIEW })
      assert.equal(data.tableType, 'VIEW')
      assert.deepEqual(data.permissions, { insert: false, edit: false })
      const response = await call('insert', { values: { ID: '1', NAME: 'x' } }, { table: VIEW })
      assert.equal(response.status, 403)
    })

    await t.test('delete requires confirmation, removes one row and reports a stale second delete', async () => {
      const page = await rows({ sort: 'ID' })
      const victim = page.rows[page.rows.length - 1]
      const body = { key: { ID: victim.ID }, original: victim }
      assert.equal((await call('delete', body)).status, 400)
      assert.equal((await call('delete', { ...body, confirm: true })).status, 200)
      assert.equal((await call('delete', { ...body, confirm: true })).status, 409)
    })

    await t.test('malformed JSON, cross-origin and oversized bodies are rejected over real HTTP', async () => {
      const malformed = await fetch(`${origin}/wangtie-os/api/oceanbase/rows`, { method: 'POST', headers: { origin, 'content-type': 'application/json' }, body: '{bad' })
      assert.equal(malformed.status, 400)
      assert.match((await malformed.json() as any).error, /JSON/)
      const foreign = await fetch(`${origin}/wangtie-os/api/oceanbase/rows`, { method: 'POST', headers: { origin: 'https://other.example', 'content-type': 'application/json' }, body: '{}' })
      assert.equal(foreign.status, 403)
      const large = await fetch(`${origin}/wangtie-os/api/oceanbase/rows`, { method: 'POST', headers: { origin, 'content-type': 'application/json' }, body: JSON.stringify({ padding: 'x'.repeat(1024 * 1024 + 1) }) })
      assert.equal(large.status, 413)
    })

    await t.test('a row locked by another session ends as an unconfirmed write, never a silent commit', { timeout: 60_000 }, async () => {
      const original = (await rows({ sort: 'ID' })).rows[0]
      await admin.execute(`SELECT * FROM ${target} WHERE ID = :1 FOR UPDATE`, { 1: original.ID })
      try {
        const response = await call('update', { key: { ID: original.ID }, original, values: { NAME: 'MUST NOT COMMIT' } })
        assert.equal(response.data.uncertain, true, JSON.stringify(response.data))
        assert.ok([503, 504].includes(response.status), `unexpected status ${response.status}`)
      } finally {
        await admin.rollback()
      }
      const current = (await rows({ sort: 'ID' })).rows[0]
      assert.notEqual(current.NAME, 'MUST NOT COMMIT')
    })
  } finally {
    for (const statement of created.reverse()) await exec(`DROP ${statement}`).catch(() => { /* 已删除 */ })
    await admin.close()
    disposers.forEach(dispose => dispose())
    server.closeAllConnections()
    await new Promise<void>(resolve => server.close(() => resolve()))
  }
})
